#:schema node_modules/wrangler/config-schema.json
name = "linkme-intops"
compatibility_date = "2026-06-30"

# Configuration for Cloudflare Pages
# Note: Cloudflare Pages projects do not use the [site] block (which is deprecated).

[vars]
NODE_VERSION = "20"
VITE_APP_ENV = "production"
